version: '3.5'

services:
    db:
      image: postgres
      restart: unless-stopped
      environment: 
        POSTGRES_PASSWORD: example
      container_name: postgres
    redis:
      image: redis:alpine
    back:
      image: 'ex11'
      build: .
      ports:
        - 8000:8000
      volumes: 
        - ./logs.txt:/home/node/logs.txt
      environment: 
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=example
        - DB_HOST=postgres
    
    front:
      image: 'ex10'
      ports:
        - 5000:5000