FROM node:10-alpine

USER node
EXPOSE 5000
WORKDIR /home/node
ENV NODE_ENV=production

ADD . .

RUN set -x \
  && npm install \
  && npm run build \
  && addgroup node \
  && adduser -D -G node node \
  && chown -R node:node /home/node

ENTRYPOINT ["npm", "start"]