version: '3.5'

services:
    db:
      image: postgres
      restart: unless-stopped
      environment: 
        POSTGRES_PASSWORD: example
      container_name: postgres

    redis:
      image: redis:alpine

    back:
      image: 'ex11'
      build: .
      volumes: 
        - ./logs.txt:/home/node/logs.txt
      environment: 
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=example
        - DB_HOST=postgres
      depends_on: 
        - postgres      
    
    front:
      image: 'ex10'
      build:
        context: .
        args: 
          API_URL: '/api'

    nginx:
      image: nginx:alpine
      restart: unless-stopped
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
