version: '3'

services:
    redis:
      image: redis:alpine
    back:
      image: 'ex11'
      build: .
      ports:
        - 8000:8000
      volumes: 
        - ./logs.txt:/usr/app/logs.txt
      environment: 
        - REDIS=redis
    
    front:
      image: 'ex10'
      ports:
        - 5000:5000